#WARNING: LOUD
#Youkai Girl at the Gate - Touhou Project
sample "C:/Users/zaid_hairil/Music/touhou_samples.wav", amp: 2, release: 1
sleep 6
use_synth :dsaw
use_synth_defaults amp: 5
live_loop :stage_2_boss do
  2.times do
    play :Fs4
    sleep 0.2
    play :B4
    sleep 0.2
    play :B4
    sleep 0.4
    play :Cs5
    sleep 0.2
    play :Cs5
    sleep 0.4
    play :Fs4
    sleep 0.2
    play :Fs4
    sleep 0.4
    play :Cs5
    sleep 0.2
    play :D5, attack: 0, sustain: 0.5, release: 0
    sleep 0.5
    play :D5, attack: 0, sustain: 0.5, release: 0
    sleep 0.5
    play :Cs5
    sleep 0.4
    play :B4
    sleep 0.2
    play :B4
    sleep 0.4
    play :Cs5
    sleep 0.2
    play :Cs5
    sleep 0.4
    play :Fs4
    sleep 0.2
    play :Fs4
    sleep 0.4
    play :B4
    sleep 0.2
    play :E5
    sleep 0.2
    play :D5
    sleep 0.2
    play :Cs5
    sleep 0.2
    play :B4
    sleep 0.2
    play :Cs5
    sleep 0.2
    play :D5
    sleep 0.2
    play :Fs4
    sleep 0.2
    play :B4
    sleep 0.2
    play :B4
    sleep 0.4
    play :Cs5
    sleep 0.2
    play :Cs5
    sleep 0.4
    play :Fs4
    sleep 0.2
    play :Fs4
    sleep 0.4
    play :Cs5
    sleep 0.2
    play :D5, attack: 0, sustain: 0.5, release: 0
    sleep 0.5
    play :D5, attack: 0, sustain: 0.5, release: 0
    sleep 0.5
    play :Cs5
    sleep 0.4
    play :As4
    sleep 0.2
    play :As4
    sleep 0.4
    play :Cs5
    sleep 0.2
    play :Cs5
    sleep 0.4
    play :Fs4
    sleep 0.2
    play :Fs4
    sleep 0.4
    play :Fs5
    sleep 0.2
    play :E5
    sleep 0.2
    play :D5
    sleep 0.2
    play :Cs5
    sleep 0.2
    play :B4
    sleep 0.2
    play :Cs5
    sleep 0.2
    play :D5
    sleep 0.4
  end
  sleep 0.6
  play :Fs4
  play :As4
  sleep 0.4
  play :As4
  play :Cs5
  sleep 0.4
  play :As4
  play :Ds5
  sleep 0.6
  play :As4
  play :F5
  sleep 1
  play :Fs4
  play :As4
  sleep 0.8
  play :As4
  sleep 0.2
  play :Cs5
  sleep 0.2
  play :As4
  play :Ds5
  sleep 0.4
  play :Ds5
  play :Gs5
  sleep 0.4
  play :Cs5
  play :Fs5
  sleep 0.4
  play :Cs5
  play :F5
  sleep 0.2
  play :As4
  play :Ds5
  sleep 0.4
  play :D5
  play :F5
  sleep 0.4
  play :As4
  play :D5
  sleep 0.4
  play :B4
  play :Ds5
  sleep 0.4
  play :Cs5
  play :F5
  sleep 0.8
  play :As4
  play :Ds5
  sleep 0.8
  play :Cs5
  play :F5
  sleep 0.8
  play :Cs5
  play :Fs5
  sleep 1
  play :Fs5
  sleep 0.2
  play :Gs5
  sleep 0.2
  play :Fs5
  play :As5
  sleep 0.2
  play :Gs5
  sleep 0.2
  play :Fs5
  sleep 0.2
  play :F5
  sleep 0.2
  play :Ds5
  sleep 0.2
  play :As4
  sleep 0.2
  play :Gs4
  sleep 0.2
  play :Fs4
  sleep 0.2
  play :F4
  play :D4
  sleep 0.4
  play :As3
  play :F4
  sleep 0.4
  play :B3
  play :Ds4
  sleep 0.4
  play :Cs4
  play :F4
  sleep 0.6
  play :As4
  play :Ds5
  sleep 0.8
  play :As4
  play :F5
  sleep 0.8
  play :Fs4
  play :As4
  sleep 0.8
  play :As4
  sleep 0.2
  play :Cs5
  sleep 0.2
  play :As4
  play :Ds5
  sleep 0.4
  play :Ds5
  play :Gs5
  sleep 0.4
  play :Cs5
  play :Fs5
  sleep 0.4
  play :Cs5
  play :F5
  sleep 0.2
  play :As4
  play :Ds5
  sleep 0.4
  play :D5
  play :F5
  sleep 0.4
  play :As4
  play :D5
  sleep 0.4
  play :B4
  play :Ds5
  sleep 0.4
  play :Cs5
  play :F5
  sleep 0.8
  play :As4
  play :Ds5
  sleep 0.8
  play :Cs5
  play :F5
  sleep 0.8
  play :Cs5
  play :Fs5
  sleep 1
  play :Fs5
  sleep 0.2
  play :Gs5
  sleep 0.2
  play :Fs5
  play :As5
  sleep 0.2
  play :Gs5
  sleep 0.2
  play :Fs5
  sleep 0.2
  play :F5
  sleep 0.2
  play :Ds5
  sleep 0.2
  play :As4
  sleep 0.2
  play :Gs4
  sleep 0.2
  play :Fs4
  sleep 0.2
  play :B4
  play :D5
  sleep 2
end

live_loop:drums_from_real_song do
  sample "C:/Users/zaid_hairil/Music/YoukaiGirlAtTheGate_sample.wav", amp: 5
  sleep 55
end